### ISSUE TITLE
Automatically generate SDK docs as much as possible

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/docs#139]
There are probably tools in various languages which help with generation of API docs based on the code. We should utilise them as opposed to writing all the docs for those ourselves.

TODO:
- TS related:
   - [x] Using typedoc
   - [x] description of functions and params
   ```
   /**
     * Get a user object from their ID
     * @param userId is the userID
     */
    static getUserById(userId: string) {
        return 
        Recipe.getInstanceOrThrowError().recipeInterfaceImpl.getUserById({ userId });
    }
   ```
   - [x] Figuring out integration with docusaurus (see https://www.npmjs.com/package/docusaurus-plugin-typedoc)
- Python
   - [x] Using pdoc
   - [x] Remove unnecessary copyright stuff
   - [x] description of functions and params
   ```
   def someFunc():
      """Describe someFunc"""
      ....
   ```
   - [x] Figuring out integration with docusaurus and pdoc
- Golang

# TODO:
- [x] moving docs from SDK repo to main-website on push to master branch (latest version, and version specific folder)
   - [x] nodejs
   - [x] python
   - [x] auth-react
   - [x] website
   - [x] react-native
- [ ] Adding version header on SDK docs
- [x] Changing docusaurus to not show the latest version warning
- [x] Changing docusaurus to not show Next version
- [x] Removing currently (latest) built version for nodejs and others
- [x] Changing links to recipe docs to point to correct SDK docs
- [x] Adding /docs/python, /docs/golang, /docs/website, /docs/auth-react redirect path in node server
- [x] Update sitemap on main site
- [x] Remove:
   - [x] python
   - [x] golang
   - [x] react-native

**Comment by rishabhpoddar** [comment]
@mufassirkazi you need to design the version header for these docs please. Keep it simple.

**Comment by rishabhpoddar** [comment]
@st-jay , @nkshah2 feedback:
- [ ] For react native docs, I see 1.2.X in the drop down, and in the older version page.. so it's not supposed to be in the drop down. Is this error there for other docs as well?
- [ ] The UI for version is very, very small.. it's very easy to miss. It should be way more prominent which version you are vewing. @mufassirkazi

**Comment by st-jay** [comment]
@rishabhpoddar I added those versions which were not displayed in the older version page, will remove the same for react-native and supertokens-website for which the versions are present in the older versions page

**Comment by rishabhpoddar** [comment]
The older version button that you have made should take the user to the docusaurus v2 docs. That will then also have an older version in its drop down which will take the user to docusaurus v1 docs (which you don't have to care about). Anyway.. as long as what you have done works, makes sense and won't cause any issues in the future, I am good with it.

**Comment by st-jay** [comment]
I think that removing the v2 docs links would be clear for the user, as it takes the user to a different page entirely

**Comment by mufassirkazi** [comment]
>  The UI for version is very, very small.. it's very easy to miss. It should be way more prominent which version you are vewing. 

**Alternatives:**

- https://zpl.io/bzzj1v7
- https://zpl.io/VQ3d9GP
- https://zpl.io/b6w9Y5m

**Comment by st-jay** [comment]
The third option stands out, but it feels out of theme and don't like the first one much
The second one is good, subtle yet stands out

**Comment by rishabhpoddar** [comment]
I like the third option the most (https://app.zeplin.io/project/5aaa0de98d835c7b25637f2e/screen/617011ebf923669353b76653)

**Comment by rishabhpoddar** [comment]
@nkshah2 @st-jay this is pushed to production.

**Comment by rishabhpoddar** [comment]
Reopening this issue since there is a mobile responsivness issue:
![Screenshot 2021-11-11 at 22.56.27.png](https://images.zenhubusercontent.com/60df055a26df4b7a2fb68f0e/d11f72f4-7062-4899-bcf6-4c151f1ca24c)
