### ISSUE TITLE
Documentation structure rework

### ISSUE THREAD

**Issue by nkshah2** [supertokens/docs#438]
## Third party email password

https://petite-salesman-0d8.notion.site/Third-Party-Email-Password-274dd6fc1a72467b8e94b63a6b2533ac

## Third party passwordless

https://petite-salesman-0d8.notion.site/Third-party-Passwordless-21f3ff40044849a096bb743fd62ede76

## TODOs

- [x] What should we do about session recipe's quick setup and integration guide?
- [ ] Check that axios interception is not there anymore in the docs
- [ ] Remove the use of `Are you using https://try.supertokens.com as the connection URI in the init function?` question.
- [ ] Remove `Set up your email / sms delivery method` section from everywhere in setup
- [x] iOS language type checking
- [x] iOS language type checking in CICD
- [ ] Temporary redirect from backend server for all routes that have redirection on the frontend
- [x] iOS code snippets
- [ ] In steps for quick setup, instead of `1)`, we should do `1.`
- [ ] android and ios code snippet for sign in with apple
- [ ] ios code snippet for sign in with google
- [x] iOS code snippet in handling session tokens

**Comment by nkshah2** [comment]
Implementation Notes (Things to keep in mind when actually working on this)
- We need to make the use of apiGatewayPath more prominent
