### ISSUE TITLE
Improvement list 2

### ISSUE THREAD

**Issue by jscyo** [supertokens/docs#79]
## Related Issue
#5 

## Tasks
- [ ] appInfo improvements:
  - [ ] That you should use env vars to determine what the value of website domain is and stuff (not doing)
  - [ ]  In quick setup, frontend & backend, mention about apiBasePath etc in appInfo
- [x] Connecting to db from docker run, say that localhost is not an option to give, and also say how to make db listen on all IPs in local machine
- [ ] Add min and max session timeout (not doing since there is no max, and min i 1 second..)
- [x] Add how to add SSL via Nginx
- [ ] For the session recipe, in about appInfo, we should have an important note under websiteDomain section that the value doesn’t really matter for this recipe.(on the backend). But it matters on the frontend (not valid)
