### ISSUE TITLE
Migrate to docusaurus v2

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/docs#8]
## TODO:
- [x] svg supertokens logo icon: https://supertokens.slack.com/archives/DRZDA5CUC/p1626092146006400
- [x] navbar logo resizing
- [x] driftt chat
- [x] Overall theme styling and colours
- [x] Change contributing readme in docs
- [x] Create latest versions of all the docs
- [ ] Algolia search is isolated properly per recipe and per version (maybe we can't add tags..).
- [x] Recipe name in recipe docs
- [x] Linking to older versions of the docs
- [x] Multi docs instance
- [x] Sub tabs styling
- [x] Meta tags for SEO in <head>
- [x] multiple instances of docs
- [x] footer: https://github.com/supertokens/docs/blob/docusaurus-v2-feasibility/community/supertokens-docs-plugin/index.js
   - Use plugin to add footer?
- [x] build process.
- [x] clicking on header buttons should take you to the right place
- [x] making community docs
   - [x] checking if redirection happens properly for certain docs
   - [x] hiding items in the sidebar
   - [x] getting stared page embed
   - [x] compatibility table
- [x] copy docs
- [x] analytics: https://github.com/supertokens/docs/blob/docusaurus-v2-feasibility/community/src/theme/Root.js
- [x] Is `TO_CHANGE.md` still relevant?
- [x] Check edit links
- [x] Check SEO meta tags + make sure og:url and twitter:url change on navigation + check social preview
- [x] remove docs meta data from sheetsdb
- [x] remove old recipe docs
- [x] Do a global search for `__END_HIGHLIGHT__` or `__` and other old ways of highlighting code and make sure they are all gone
- [x] Do a global search on `<!--DOCUSAURUS_CODE_TABS-->` and remove them.

**Comment by rishabhpoddar** [comment]
v2 supprts code highlighting out of the box, so we can also get rid of our code highlighting method.

**Comment by rishabhpoddar** [comment]
In V1, we hack around with some JS to make a top level side bar item into a page. Is that possible in v2 without the same hack?

**Comment by rishabhpoddar** [comment]
@mufassirkazi please create a supertokens logo thats on the top left of our docs in .svg format.

**Comment by mufassirkazi** [comment]
https://supertokens.slack.com/archives/DRZDA5CUC/p1626092146006400

**Comment by rishabhpoddar** [comment]
@mufassirkazi , I need equivalent colours for the below, but for our colour scheme:
```
:root {
  --ifm-color-primary: #25c2a0;
  --ifm-color-primary-dark: rgb(33, 175, 144);
  --ifm-color-primary-darker: rgb(31, 165, 136);
  --ifm-color-primary-darkest: rgb(26, 136, 112);
  --ifm-color-primary-light: rgb(70, 203, 174);
  --ifm-color-primary-lighter: rgb(102, 212, 189);
  --ifm-color-primary-lightest: rgb(146, 224, 208);
  --ifm-code-font-size: 95%;
}
```

So `#25c2a0` should be `#ff9933`. And then accordingly, what should the others be?

**Comment by rishabhpoddar** [comment]
@mufassirkazi, docusaurus has a way to get colours (see https://docusaurus.io/docs/styling-layout). I used that, and got the following:
```
:root {
  --ifm-color-primary: #ff9933;
  --ifm-color-primary-dark: #ff8a14;
  --ifm-color-primary-darker: #ff8205;
  --ifm-color-primary-darkest: #d66b00;
  --ifm-color-primary-light: #ffa852;
  --ifm-color-primary-lighter: #ffb061;
  --ifm-color-primary-lightest: #ffc78f;
  --ifm-code-font-size: 95%;
}
```

**Comment by rishabhpoddar** [comment]
Feedback from @makerboiAdi 
- I think column width is far too large. Readability and text size of current is much better
- Emailpassword + social login recipe card and only social login recipe card do not look distinct. no gap between them
- In the architecture diagram:
   - everything is colour coded - which is good. But there is this red element on the frontend that isnt explained when everything else is
   - Why is the frontend driver interface and core driver interface shown as distinct elements. Adds unneeded complexity? Validate input and verify session can be shown within the yellow box itself.
- Can we colour code the support tech stacks section in the intro? Green for Nodejs, orange for python / Golang and red for php / java
Same scheme for the frontend
- When you click on a recipe, the common customizations sub items are open by default. why? Can we not do that?

**Comment by rishabhpoddar** [comment]
@makerboiAdi 

> I think column width is far too large. Readability and text size of current is much better

This would take a while to fix. But @mufassirkazi please see how the styling of the docs can change to make these things better.

> Why is the frontend driver interface and core driver interface shown as distinct elements. Adds unneeded complexity?

Cause we mention these terms in the API reference page. So adding these terms here makes it easier to understand them. For users that don't care about the API reference page, these terms can be unnecessary, but then they might just ignore it?

@mufassirkazi please see the other points in the "In the architecture diagram" in the previous comment and change the image if required.
